import uuid
from sqlalchemy import Column, Text, Boolean, TIMESTAMP, ForeignKey, Integer, SmallInteger, BigInteger, Index
from sqlalchemy.dialects.postgresql import UUID, JSONB
from sqlalchemy.sql import func
from sqlalchemy.orm import relationship

from db.database import Base

class Organization(Base):
    __tablename__ = "organizations"

    org_id = Column(UUID(as_uuid=True), primary_key=True, server_default=func.gen_random_uuid())
    name = Column(Text, nullable=False)
    created_at = Column(TIMESTAMP, nullable=False, server_default=func.now())

    enrollment_tokens = relationship("EnrollmentToken", back_populates="organization")
    agents = relationship("Agent", back_populates="organization")


class EnrollmentToken(Base):
    __tablename__ = "enrollment_tokens"

    token = Column(Text, primary_key=True)
    created_at = Column(TIMESTAMP, nullable=False, server_default=func.now())
    expires_at = Column(TIMESTAMP, nullable=False)
    used = Column(Boolean, nullable=False, default=False)

    # Reverse relationship: lets you do enrollment_token.agents to see all agents that used this token
    agents = relationship("Agent", back_populates="enrollment_token_obj")

    tenant_id = Column(UUID(as_uuid=True), ForeignKey("organizations.org_id"), nullable=False)

    organization = relationship("Organization", back_populates="enrollment_tokens")


class Agent(Base):
    __tablename__ = "agents"

    agent_id = Column(UUID(as_uuid=True), primary_key=True, server_default=func.gen_random_uuid())
    hostname = Column(Text, nullable=False)
    os = Column(Text, nullable=False)
    api_key = Column(Text, nullable=False, unique=True)
    status = Column(Text, nullable=False, default="active")
    enrollment_token = Column(Text, ForeignKey("enrollment_tokens.token"))
    created_at = Column(TIMESTAMP, nullable=False, server_default=func.now())
    last_seen_at = Column(TIMESTAMP)
    ip_address = Column(Text)
    mac_address = Column(Text)

    enrollment_token_obj = relationship("EnrollmentToken", back_populates="agents")

    tenant_id = Column(UUID(as_uuid=True), ForeignKey("organizations.org_id"), nullable=False)

    organization = relationship("Organization", back_populates="agents")
    events = relationship("Event", back_populates="agent")


class User(Base):
    __tablename__ = "users"

    user_id = Column(UUID(as_uuid=True), primary_key=True, server_default=func.gen_random_uuid())
    username = Column(Text, nullable=False, unique=True)
    password_hash = Column(Text, nullable=False)
    created_at = Column(TIMESTAMP, nullable=False, server_default=func.now())


class Event(Base):
    """
    OCSF-based event envelope. Base Event fields are indexed columns;
    class-specific fields (process{}, file{}, network{}, etc.) live in `data`.
    See docs/phase2-event-schema.md for the field-level spec.

    Mirrors `\\d events` in psql. NOTE: `time` and `created_at` on this table
    are timestamptz (timezone=True), unlike the other tables, which are still
    timestamp without time zone. Always pass tz-aware UTC datetimes here.
    """
    __tablename__ = "events"

    # = metadata.uid from the OCSF envelope, generated by the agent per event
    event_id = Column(UUID(as_uuid=True), primary_key=True, server_default=func.gen_random_uuid())

    time = Column(TIMESTAMP(timezone=True), nullable=False)  # UTC, from the agent — not created_at
    class_uid = Column(Integer, nullable=False)
    category_uid = Column(Integer, nullable=False)
    activity_id = Column(Integer, nullable=False)
    type_uid = Column(BigInteger, nullable=False)  # class_uid * 100 + activity_id
    severity_id = Column(Integer, nullable=False)

    hostname = Column(Text)
    username = Column(Text)

    # Postgres currently allows NULL here (see \d events). The WS handler always sets it.
    # To tighten: ALTER TABLE events ALTER COLUMN agent_id SET NOT NULL; then add nullable=False below.
    agent_id = Column(UUID(as_uuid=True), ForeignKey("agents.agent_id"))

    # Denormalized from Agent.tenant_id at insert time — never trust a client-supplied value here
    tenant_id = Column(UUID(as_uuid=True), ForeignKey("organizations.org_id"), nullable=False)

    metadata_ = Column("metadata", JSONB)  # `metadata` is reserved on Declarative Base, hence the alias
    data = Column(JSONB, nullable=False)   # class-specific fields: process{}, file{}, network{}, etc.

    created_at = Column(TIMESTAMP(timezone=True), nullable=False, server_default=func.now())

    # Envelope fields added Sept 18
    schema_version = Column(SmallInteger, nullable=False, server_default="1")  # agent-supplied
    agent_version = Column(Text)                                               # agent-supplied
    host_os = Column(Text)                                                     # agent-supplied: windows / linux
    host_os_version = Column(Text)                                             # agent-supplied
    ingest_source = Column(Text, nullable=False, server_default="websocket")   # SERVER-set only, never from client

    agent = relationship("Agent", back_populates="events")
    alerts = relationship("Alert", back_populates="event")

    __table_args__ = (
        Index("idx_events_class", "class_uid"),
        Index("idx_events_time", "time"),
        Index("idx_events_host", "hostname"),
        Index("idx_events_tenant", "tenant_id"),
        Index("idx_events_data", "data", postgresql_using="gin"),
    )


class Alert(Base):
    """
    OCSF Detection Finding (class_uid 2004). Derived from an Event by a
    Phase 3 rule or a Phase 5 ML model — kept separate since alerts are
    derived records, not raw telemetry.
    """
    __tablename__ = "alerts"

    alert_id = Column(UUID(as_uuid=True), primary_key=True, server_default=func.gen_random_uuid())
    event_id = Column(UUID(as_uuid=True), ForeignKey("events.event_id"), nullable=False)

    class_uid = Column(Integer, nullable=False, default=2004)
    technique_id = Column(Text)     # MITRE ATT&CK tag, e.g. "T1566"
    d3fend_action = Column(Text)    # recommended defense
    risk_score = Column(Integer)
    source = Column(Text)           # 'rule' or 'ml_anomaly'
    requires_review = Column(Boolean, nullable=False, default=False)

    created_at = Column(TIMESTAMP, nullable=False, server_default=func.now())

    event = relationship("Event", back_populates="alerts")